repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.5
  hooks:
    - id: terraform_fmt
      args: ['--recursive']
    - id: terraform_validate
    - id: terraform_tflint
      args:
        - '--config=.tflint.hcl'
    - id: terraform_docs
    - id: terraform_checkov
      args:
        - '--config-file'
        - '.checkov.yaml'
    - id: terraform_tfsec
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-added-large-files
      args: ['--maxkb=500']
- repo: local
  hooks:
    - id: lambda-test
      name: Test Lambda Functions
      entry: scripts/test-lambda.sh
      language: script
      files: '^lambda/'
      pass_filenames: false
    - id: infrastructure-test
      name: Test Infrastructure
      entry: scripts/test-infrastructure.sh
      language: script
      pass_filenames: false
      stages: [push]
