repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.5
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_docs
    - id: terraform_tflint
      args:
        - '--args=--only=terraform_deprecated_interpolation'
        - '--args=--only=terraform_deprecated_index'
        - '--args=--only=terraform_unused_declarations'
        - '--args=--only=terraform_comment_syntax'
        - '--args=--only=terraform_documented_outputs'
        - '--args=--only=terraform_documented_variables'
        - '--args=--only=terraform_typed_variables'
        - '--args=--only=terraform_naming_convention'
        - '--args=--only=terraform_required_version'
        - '--args=--only=terraform_required_providers'
        - '--args=--only=terraform_standard_module_structure'
    - id: terraform_checkov
      args:
        - --args=--quiet
        - --args=--framework=terraform
        - --args=--skip-check=CKV_AWS_79,CKV_AWS_126

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-json
    - id: detect-private-key
    - id: mixed-line-ending
      args: ['--fix=lf']

- repo: local
  hooks:
    - id: update-readme
      name: Update README.md with terraform-docs
      entry: ./scripts/update-docs.sh
      language: script
      files: ^(README\.md|\.terraform-docs\.yml)$
      pass_filenames: false
